services:
  - name: zeninventory-db
    type: pserv
    env: docker
    plan: free
    autoDeploy: false
    dockerfile: docker/mariadb/Dockerfile-mariadb
    disk:
      name: mariadb
      mountPath: /var/lib/mariadb
      sizeGB: 4GB
  - name: zeninventory-app
    type: web
    plan: free
    env: docker
    dockerfile: ./docker/Dockerfile-java17maven
    envFrom:
      - service: zeninventory-db
