services:
  db:
    image: mariadb
    context: ./docker/mariadb
    dockerfile: Dockerfile-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: databaseAdmin
      MYSQL_DATABASE: zeninventory
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
  app:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile-java17spring
    environment:
      SPRING_DATASOURCE_URL: mariadb://db:3306/zeninventory
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: databaseAdmin
    ports:
      - 8080:8080
    depends_on:
      - db
volumes:
  db-data: