#
# Use buildpacks to create a layered code image for Spring Boot application
# more efficient, secure, and easier to maintain
#
# Use the official OpenJDK 17 image as the base image
FROM openjdk:17-alpine

# Install the Buildpacks
RUN apk add --no-cache curl tar && \
    curl -sSL https://github.com/buildpacks/pack/releases/download/v0.21.1/pack-v0.21.1-linux.tgz | tar -C /usr/local/bin -xzf - && \
    apk del curl tar && \
    pack --version

# Set the working directory to /app
WORKDIR /app

# Copy the Spring Boot application to the container
COPY . /app

# Build the application using the Buildpacks
RUN pack build zeninventory-app --builder paketobuildpacks/builder:base --path . --env BP_JVM_VERSION=17 --env BP_MAVEN_BUILT_ARTIFACT=zeninventory.jar

# Set the entry point to the Spring Boot application
ENTRYPOINT ["java", "-jar", "/zeninventory-app/zeninventory.jar"]